# Provide the settings for the backend API.

# Debug options can be enabled for the server, for the DB, or both.
# When all debug options are present the generic one is applied first, and then overwritten by section-based options.

debug  = false

[server]
host   = "0.0.0.0"
port   = 8080
bearer = "bearer_token_here"
debug  = false

[database]
server = "127.0.0.1"
dbname = "chai"
user   = "api_access"
pass   = "db_password_here"
debug  = false

[pushover]
user   = "unej..."
app    = "a1v6..."

[profiles]
number = 2

[profiles.1]
mean1 = 23
mean2 = -0.05
variance1 = 1
variance2 = 0.01
noiseprecision = 0.1
correlation1 = 0
correlation2 = 0
region_angle = 360
region_width = 0.4
region_height = 4.0
prediction_banded = [[14.46, 23.0, 31.54], [14.4, 22.95, 31.5]]

[profiles.2]
mean1 = 23
mean2 = -0.05
variance1 = 1
variance2 = 0.01
noiseprecision = 0.1
correlation1 = 0
correlation2 = 0
region_angle = 360
region_width = 0.4
region_height = 4.0
prediction_banded = [[14.46, 23.0, 31.54], [14.4, 22.95, 31.5]]